#!/bin/sh
APP_ROOT=/var/myapp
ENV=production
# Remember to use same PID path in your Pipefile.
PID=/var/run/pipemaster.pid
CMD="pipemaster -D -E $ENV"
 
old_pid="$PID.oldbin"
 
cd $APP_ROOT || exit 1
 
sig () {
    test -s "$PID" && kill -$1 `cat $PID`
}
oldsig () {
    test -s $old_pid && kill -$1 `cat $old_pid`
}
 
case $1 in
start)
	sig 0 && echo >&2 "Already running" && exit 0
	$CMD
	;;
stop)
	sig QUIT && exit 0
	echo >&2 "Not running"
	;;
force-stop)
	sig TERM && exit 0
	echo >&2 "Not running"
	;;
restart|reload)
	sig HUP && echo reloaded OK && exit 0
	echo >&2 "Couldn't reload, starting '$CMD' instead"
	$CMD
	;;
upgrade)
	sig USR2 && sleep 3 && sig 0 && oldsig QUIT && exit 0
	echo >&2 "Couldn't upgrade, starting '$CMD' instead"
	$CMD
	;;
status)
    sig 0 && echo >&2 "Running" && exit 0
	echo >&2 "Not running"
    ;;
*)
	echo >&2 "Usage: $0 <start|stop|status|restart|upgrade|force-stop>"
	exit 1
	;;
esac
